site_name: bxtctl
repo_url: https://gitlab.manjaro.org/fhdk/bxtctl
docs_dir: docs
use_directory_urls: false
theme:
  name: readthedocs
nav:
    - Home: index.md
    - Installation: installation.md
    - Usage: usage.md
